-- ============================================================================
-- Migração: tabela `stories` (Vídeos/Stories do painel admin)
-- ============================================================================
-- Decisões confirmadas com a Amanda (21/08/2026):
--   - Único campo do cadastro é o Título; "Cadastrado em" é automático.
--   - Expiração é automática: momento do cadastro + 24 horas (sem campo no
--     formulário — por isso `expires_at` já nasce calculado a partir de
--     `created_at`, não é algo que o admin escolhe).
--   - `video_path`/`thumbnail_url` guardam só o caminho no Bunny Stream (a
--     URL final é resolvida no front, igual já fazemos pras imagens — ver
--     `resolveBunnyVideoUrl` em `src/lib/bunnyStorage.ts`). Ficam nullable
--     porque o upload real (Bunny) ainda não está conectado (falta a Amanda
--     passar a API key/Library ID) — a tela já funciona de verdade pra
--     título/data/exclusão, só o arquivo de vídeo em si que fica pendente.
--
-- RLS: select liberado pra qualquer usuário logado (o app cliente também
-- precisa ler os stories ativos pra exibir na tela). Insert liberado pra
-- master_admin, editor_conteudo E convidado — é a exceção já prevista no
-- comentário da migration 0001 ("a única função do Convidado no painel é
-- subir vídeos na área de Stories"). Delete ficou só com master_admin, pelo
-- mesmo padrão usado em stores/categories (ação irreversível) — não tinha
-- ficado 100% explícito pro Convidado no plano original, então fiz a opção
-- mais conservadora; avisa se quiser liberar delete pro Convidado também.
-- ============================================================================

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  title text not null,
  video_path text,
  thumbnail_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

alter table public.stories enable row level security;

create policy "stories_select_authenticated"
  on public.stories for select
  to authenticated
  using (true);

-- Enumera os 3 níveis com acesso (não usei `is_team_member`/`can_manage_catalog`
-- de propósito: Suporte é membro da equipe mas NÃO deveria poder subir
-- stories por esse acesso genérico, e Convidado não se qualifica em
-- `can_manage_catalog` mesmo tendo permissão aqui — por isso a checagem é
-- explícita aos 3 níveis certos, em vez de reaproveitar uma função existente
-- que não bate exatamente com essa regra).
create policy "stories_insert_team"
  on public.stories for insert
  to authenticated
  with check (
    exists (
      select 1 from public.team_members tm
      where tm.user_id = auth.uid()
        and tm.access_level in ('master_admin', 'editor_conteudo', 'convidado')
    )
  );

create policy "stories_delete_master_admin"
  on public.stories for delete
  to authenticated
  using (public.is_master_admin(auth.uid()));
