-- ============================================================================
-- Migração: notificações reais (sino da Início/TopBar + tela `/notificacoes`)
-- ============================================================================
-- Antes disso, `NotificationsContext.tsx` FABRICAVA notificações client-side
-- a partir das últimas lojas cadastradas (`listRecentStores`) — não existia
-- histórico de verdade, "lida/não lida" era um índice arbitrário (`index >=
-- 2`), e não tinha NADA sobre Stories. A Amanda confirmou (22/08/2026)
-- que quer exatamente 2 tipos de notificação reais, aparecendo pra
-- qualquer usuário logado:
--   1. Um fornecedor novo sobe na plataforma (loja fica visível/ativa).
--   2. Um story novo sobe ("Novo Stories").
--
-- Design:
--   - `notifications`: uma linha por evento, alimentada por TRIGGER (não
--     por insert direto do front) — dispara sozinho quando uma loja vira
--     `is_active = true` (cadastro já ativo OU reativada depois) e quando
--     um story novo é criado. Nunca é apagada por usuário nenhum; é um
--     feed histórico, igual notificação de qualquer app.
--   - `notification_reads`: 1 linha por usuário, guardando só
--     `last_read_at`. "Lida" = `notifications.created_at <=
--     notification_reads.last_read_at` — assim "marcar todas como lidas"
--     é só um upsert de timestamp, sem precisar de uma linha por
--     notificação por usuário (economia, e cobre notificações antigas que
--     a pessoa nunca tinha visto ainda quando logou pela primeira vez).
-- ============================================================================

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('new_store', 'new_story')),
  title text not null,
  description text not null,
  created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;

-- Select liberado pra qualquer usuário logado (cliente final E equipe) —
-- é um feed público dentro do app, não tem dado sensível por linha.
create policy "notifications_select_authenticated"
  on public.notifications for select
  to authenticated
  using (true);

-- Sem policy de insert/update/delete pra `authenticated`/`anon` de
-- propósito: só as funções SECURITY DEFINER abaixo (chamadas pelos
-- triggers) conseguem escrever aqui.

create table if not exists public.notification_reads (
  user_id uuid not null references auth.users(id) on delete cascade,
  last_read_at timestamptz not null default now(),
  primary key (user_id)
);

alter table public.notification_reads enable row level security;

create policy "notification_reads_select_own"
  on public.notification_reads for select
  to authenticated
  using (user_id = auth.uid());

create policy "notification_reads_insert_own"
  on public.notification_reads for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "notification_reads_update_own"
  on public.notification_reads for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ----------------------------------------------------------------------
-- Trigger: nova loja fica visível → notificação "Novo parceiro no app!"
-- ----------------------------------------------------------------------
-- Dispara no INSERT (loja já nasce ativa) e no UPDATE de `is_active`
-- (loja criada oculta e depois publicada) — sempre que `is_active` PASSA
-- a ser `true`. Se o admin desativar e reativar de novo, dispara outra
-- vez (aceitável: reapareceu no catálogo, é uma novidade de novo).
create or replace function public.notify_new_store()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if TG_OP = 'INSERT' then
    if NEW.is_active then
      insert into public.notifications (type, title, description)
      values ('new_store', 'Novo parceiro no app!', NEW.name || ' foi adicionado.');
    end if;
  elsif TG_OP = 'UPDATE' then
    if NEW.is_active and not OLD.is_active then
      insert into public.notifications (type, title, description)
      values ('new_store', 'Novo parceiro no app!', NEW.name || ' foi adicionado.');
    end if;
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_notify_new_store on public.stores;
create trigger trg_notify_new_store
  after insert or update of is_active on public.stores
  for each row
  execute function public.notify_new_store();

-- ----------------------------------------------------------------------
-- Trigger: novo story cadastrado → notificação "Novo Stories!"
-- ----------------------------------------------------------------------
create or replace function public.notify_new_story()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (type, title, description)
  values ('new_story', 'Novo Stories!', 'Confira agora: ' || NEW.title);
  return NEW;
end;
$$;

drop trigger if exists trg_notify_new_story on public.stories;
create trigger trg_notify_new_story
  after insert on public.stories
  for each row
  execute function public.notify_new_story();
